# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service.proto", :syntax => :proto3) do
    add_message "greeter.Person" do
      optional :first_name, :string, 1
      optional :last_name, :string, 2
    end
    add_message "greeter.Greeting" do
      optional :message, :string, 1
    end
  end
end

module Greeter
  Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.Person").msgclass
  Greeting = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.Greeting").msgclass
end
